### ISSUE TITLE
appear  android.os.BadParcelableException  error  

### ISSUE THREAD

**Issue by hfbi360** [PaNaVTEC/DrawableView#15]
Caused by: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class java.util.ArrayList
	at android.os.Parcel.readParcelableCreator(Parcel.java:2114)
	at android.os.Parcel.readParcelable(Parcel.java:2055)
	at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
	at android.view.View$BaseSavedState.<init>(View.java:19038)

**Comment by PaNaVTEC** [comment]
This is not even realted with the library

**Comment by hfbi360** [comment]
Caused by: android.os.BadParcelableException: Parcelable protocol requires that the class implements Parcelable
	at android.os.Parcel.readParcelableCreator(Parcel.java:2407)
	at android.os.Parcel.readParcelable(Parcel.java:2358)
	at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
	at android.view.View$BaseSavedState.<init>(View.java:21481)

when call 	DrawableViewSaveState$1.createFromParcel
