### ISSUE TITLE
Saving Background bitmap with drawn paint causes the app to crash?

### ISSUE THREAD

**Issue by imsocb** [PaNaVTEC/DrawableView#16]
Hi Chris, Sorry to bother you did not know have you read my previous post to you in another thread here https://github.com/PaNaVTEC/DrawableView/issues/6. Anyway, have been getting weird errors (double paint on the canvas and crashing the app) occurring when i press the save button that runs this code drawableView.obtainBitmap(bitmap);  where i want to save the drawn paint together with the background image. Rather a newbie in android please tell me how I can solve this problem? Thank You

```
 java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@c6e04c3
                                                                                               at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
                                                                                               at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
                                                                                               at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
                                                                                               at android.view.View.getDrawableRenderNode(View.java:16513)
                                                                                               at android.view.View.drawBackground(View.java:16449)
                                                                                               at android.view.View.draw(View.java:16261)
```

**Comment by PaNaVTEC** [comment]
can you provide a sample project with the bug? Happy to take a look

**Comment by imsocb** [comment]
Hi, sorry for the late reply I did provide my example code in the previous thread link here --> https://github.com/PaNaVTEC/DrawableView/issues/6 not sure have you seen it? It occur when `drawableView.obtainBitmap(OriginalBitmap); ` was called? 

Moreover, is there any way i can display my image bitmap onto the drawableView as the way the picture was taken, because at the moment drawableview omit a large part of my bitmap image when loaded onto the drawableview? Any suggestions to solve it? Thanks.
```
OriginalBitmap = ImageLoader.init().from(selectedPhoto).requestSize(512,512).getBitmap();
drawableView.setBackground(new BitmapDrawable(getResources(), OriginalBitmap));
```
