### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by oPrisonbreak** [PaNaVTEC/DrawableView#20]
Caused by: android.os.BadParcelableException: 
  at android.os.Parcel.readParcelableCreator(Parcel.java:2511)
  at android.os.Parcel.readParcelable(Parcel.java:2462)
  at android.view.AbsSavedState.<init>(AbsSavedState.java:67)
  at android.view.View$BaseSavedState.<init>(View.java:22761)
  at android.view.View$BaseSavedState.<init>(View.java:22750)
  at me.panavtec.drawableview.DrawableViewSaveState.<init>(DrawableViewSaveState.java:14)
  at me.panavtec.drawableview.DrawableViewSaveState$1.createFromParcel(DrawableViewSaveState.java:40)
  at me.panavtec.drawableview.DrawableViewSaveState$1.createFromParcel(DrawableViewSaveState.java:38)
  at android.os.Parcel.readParcelable(Parcel.java:2471)
  at android.os.Parcel.readValue(Parcel.java:2365)
  at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
  at android.os.Parcel.readSparseArray(Parcel.java:2068)
  at android.os.Parcel.readValue(Parcel.java:2422)
  at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
  at android.os.BaseBundle.unparcel(BaseBundle.java:269)
  at android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
  at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2104)
  at android.app.Activity.onRestoreInstanceState(Activity.java:1074)
  at android.app.Activity.performRestoreInstanceState(Activity.java:1029)
  at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1175)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2638)

**Comment by damien3D** [comment]
Same problem here. Did you find any solution ?
